### ISSUE TITLE
nestJSの環境変数の扱い

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve-backend-tag#2]

**Comment by Takapy1** [comment]
@Ayato-kosaka 
nestJSのservise内でElasticsearchのAPI叩くためのURLとかを環境変数で管理したいんだけど、
nestJSで環境変数どうやって使うか詳しい？

**Comment by Ayato-kosaka** [comment]
@Takapy1 返信遅くなって申し訳ない

https://github.com/Ayato-kosaka/spelieve-backend-place/blob/main/src/app.module.ts
これを参考に、envをインポートして、

https://github.com/Ayato-kosaka/spelieve-backend-place/blob/main/src/main.ts
これを参考に、app.get(ConfigService);

configService.get<string>('GOOGLE_CLOUD_API_KEY')
で使える！
